version: '3.4'

services:
  accountdefinition.database:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_init_scripts:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
  postgres_init_scripts: