version: '3.4'

services:
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    ports:
      - 29092:29092
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    ports:
      - 2181:2181
  
  postgresql.database:
    container_name: postgresql.database
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=IPLACE_DB
    restart: always
    ports:
      - 6000:5432
    volumes:
      - ./src/Services/Venue.API/_Scripts/Database/init.sql:/docker-entrypoint-initdb.d/init_venue.sql:ro
      - ./src/Services/AccountDefinition.API/_Scripts/Database/init.sql:/docker-entrypoint-initdb.d/init_accountdefinition.sql:ro
      - ./src/Services/Identity.API/_Scripts/Database/init.sql:/docker-entrypoint-initdb.d/init_identity.sql:ro
  
  category.database:
    container_name: category.database
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
      - MONGO_INITDB_DATABASE=CATEGORY_DB
    restart: always
    ports:
      - 6020:27017
    volumes:
      - ./src/Services/Category.API/_Scripts/Database:/docker-entrypoint-initdb.d:ro
      
  venuereview.database:
    container_name: venuereview.database
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
      - MONGO_INITDB_DATABASE=VENUEREVIEW_DB
    restart: always
    ports:
      - 6006:27017
    volumes:
      - ./src/Services/VenueReview.API/_Scripts/Database:/docker-entrypoint-initdb.d:ro
      
  venuelist.database:
    container_name: venuelist.database
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
      - MONGO_INITDB_DATABASE=VENUELIST_DB
    restart: always
    ports:
      - 6003:27017
    volumes:
      - ./src/Services/VenueList.API/_Scripts/Database:/docker-entrypoint-initdb.d:ro
     
  userprofile.database:
    container_name: userprofile.database
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6015:6379
  
  filestorage.database:
    container_name: filestorage.database
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
      - MONGO_INITDB_DATABASE=FILESTORAGE_DB
    restart: always
    ports:
      - 6050:27017
    volumes:
      - ./src/Services/FileStorage.API/_Scripts/Database:/docker-entrypoint-initdb.d:ro