version: '3.4'

services:
  postgresql.database:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_init_scripts:/docker-entrypoint-initdb.d/

  category.database:
    volumes:
      - category_data:/data/db
      - category_configdb:/data/configdb

  filestorage.database:
    volumes:
      - filestorage_data:/data/db
      - filestorage_configdb:/data/configdb
    
  userprofile.database:
    volumes:
      - userprofile_data:/data

volumes:
  postgres_data:
  postgres_init_scripts:
  category_data:
  category_configdb:
  userprofile_data:
  filestorage_data:
  filestorage_configdb:
